### ISSUE TITLE
Lateral movement

### ISSUE THREAD

**Issue by bymaximus** [Razor-AHRS/razor-9dof-ahrs#36]
Hi, first of all, thanks for excellent project.

Not a issue but a question, possible to calculate lateral movement too?

**Comment by olmerg** [comment]
I think that it is not possible if you do not have a model, because the translation (lateral/longitudinal/altitude) movement, would have to be obtained by the accelerometers, but when the rigid body is rotating the accelerometer would measure the sums of all the acceleration in the point of the body (translation, Coriolis, centrifugal, centripetal).

[link to wikipedia!]( https://en.wikipedia.org/wiki/Coriolis_effect#Components_of_Acceleration )
